//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 11:56:08 AM EEST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="startedPrice" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="currentPrice" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="finalPrice" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="lotStatus" type="{http://spring.io/guides/gs-producing-web-service}lotStatus"/&gt;
 *         &lt;element name="ownerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="offerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startedPrice",
    "currentPrice",
    "finalPrice",
    "lotStatus",
    "ownerId",
    "offerId"
})
@XmlRootElement(name = "getLotsRequest")
public class GetLotsRequest {

    protected int startedPrice;
    protected int currentPrice;
    protected int finalPrice;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LotStatus lotStatus;
    @XmlElement(required = true)
    protected String ownerId;
    @XmlElement(required = true)
    protected String offerId;

    /**
     * Gets the value of the startedPrice property.
     * 
     */
    public int getStartedPrice() {
        return startedPrice;
    }

    /**
     * Sets the value of the startedPrice property.
     * 
     */
    public void setStartedPrice(int value) {
        this.startedPrice = value;
    }

    /**
     * Gets the value of the currentPrice property.
     * 
     */
    public int getCurrentPrice() {
        return currentPrice;
    }

    /**
     * Sets the value of the currentPrice property.
     * 
     */
    public void setCurrentPrice(int value) {
        this.currentPrice = value;
    }

    /**
     * Gets the value of the finalPrice property.
     * 
     */
    public int getFinalPrice() {
        return finalPrice;
    }

    /**
     * Sets the value of the finalPrice property.
     * 
     */
    public void setFinalPrice(int value) {
        this.finalPrice = value;
    }

    /**
     * Gets the value of the lotStatus property.
     * 
     * @return
     *     possible object is
     *     {@link LotStatus }
     *     
     */
    public LotStatus getLotStatus() {
        return lotStatus;
    }

    /**
     * Sets the value of the lotStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link LotStatus }
     *     
     */
    public void setLotStatus(LotStatus value) {
        this.lotStatus = value;
    }

    /**
     * Gets the value of the ownerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerId(String value) {
        this.ownerId = value;
    }

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferId(String value) {
        this.offerId = value;
    }

}
