//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 11:56:08 AM EEST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetLotRequest }
     * 
     */
    public GetLotRequest createGetLotRequest() {
        return new GetLotRequest();
    }

    /**
     * Create an instance of {@link GetLotResponse }
     * 
     */
    public GetLotResponse createGetLotResponse() {
        return new GetLotResponse();
    }

    /**
     * Create an instance of {@link Lot }
     * 
     */
    public Lot createLot() {
        return new Lot();
    }

    /**
     * Create an instance of {@link GetLotsRequest }
     * 
     */
    public GetLotsRequest createGetLotsRequest() {
        return new GetLotsRequest();
    }

    /**
     * Create an instance of {@link GetLotsResponse }
     * 
     */
    public GetLotsResponse createGetLotsResponse() {
        return new GetLotsResponse();
    }

    /**
     * Create an instance of {@link UpdateLotRequest }
     * 
     */
    public UpdateLotRequest createUpdateLotRequest() {
        return new UpdateLotRequest();
    }

    /**
     * Create an instance of {@link DeleteLotRequest }
     * 
     */
    public DeleteLotRequest createDeleteLotRequest() {
        return new DeleteLotRequest();
    }

    /**
     * Create an instance of {@link GetOfferRequest }
     * 
     */
    public GetOfferRequest createGetOfferRequest() {
        return new GetOfferRequest();
    }

    /**
     * Create an instance of {@link GetOfferResponse }
     * 
     */
    public GetOfferResponse createGetOfferResponse() {
        return new GetOfferResponse();
    }

    /**
     * Create an instance of {@link Offer }
     * 
     */
    public Offer createOffer() {
        return new Offer();
    }

    /**
     * Create an instance of {@link GetOffersRequest }
     * 
     */
    public GetOffersRequest createGetOffersRequest() {
        return new GetOffersRequest();
    }

    /**
     * Create an instance of {@link GetOffersResponse }
     * 
     */
    public GetOffersResponse createGetOffersResponse() {
        return new GetOffersResponse();
    }

    /**
     * Create an instance of {@link CreateOfferRequest }
     * 
     */
    public CreateOfferRequest createCreateOfferRequest() {
        return new CreateOfferRequest();
    }

    /**
     * Create an instance of {@link UpdateOfferRequest }
     * 
     */
    public UpdateOfferRequest createUpdateOfferRequest() {
        return new UpdateOfferRequest();
    }

    /**
     * Create an instance of {@link DeleteOfferRequest }
     * 
     */
    public DeleteOfferRequest createDeleteOfferRequest() {
        return new DeleteOfferRequest();
    }

    /**
     * Create an instance of {@link GetProductRequest }
     * 
     */
    public GetProductRequest createGetProductRequest() {
        return new GetProductRequest();
    }

    /**
     * Create an instance of {@link GetProductResponse }
     * 
     */
    public GetProductResponse createGetProductResponse() {
        return new GetProductResponse();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link GetProductsRequest }
     * 
     */
    public GetProductsRequest createGetProductsRequest() {
        return new GetProductsRequest();
    }

    /**
     * Create an instance of {@link GetProductsResponse }
     * 
     */
    public GetProductsResponse createGetProductsResponse() {
        return new GetProductsResponse();
    }

    /**
     * Create an instance of {@link CreateProductRequest }
     * 
     */
    public CreateProductRequest createCreateProductRequest() {
        return new CreateProductRequest();
    }

    /**
     * Create an instance of {@link UpdateProductRequest }
     * 
     */
    public UpdateProductRequest createUpdateProductRequest() {
        return new UpdateProductRequest();
    }

    /**
     * Create an instance of {@link DeleteProductRequest }
     * 
     */
    public DeleteProductRequest createDeleteProductRequest() {
        return new DeleteProductRequest();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link GetUsersRequest }
     * 
     */
    public GetUsersRequest createGetUsersRequest() {
        return new GetUsersRequest();
    }

    /**
     * Create an instance of {@link GetUsersResponse }
     * 
     */
    public GetUsersResponse createGetUsersResponse() {
        return new GetUsersResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link CreateUserRequest }
     * 
     */
    public CreateUserRequest createCreateUserRequest() {
        return new CreateUserRequest();
    }

    /**
     * Create an instance of {@link CreateUserResponse }
     * 
     */
    public CreateUserResponse createCreateUserResponse() {
        return new CreateUserResponse();
    }

    /**
     * Create an instance of {@link UpdateUserRequest }
     * 
     */
    public UpdateUserRequest createUpdateUserRequest() {
        return new UpdateUserRequest();
    }

    /**
     * Create an instance of {@link DeleteUserRequest }
     * 
     */
    public DeleteUserRequest createDeleteUserRequest() {
        return new DeleteUserRequest();
    }

    /**
     * Create an instance of {@link DeleteUserResponse }
     * 
     */
    public DeleteUserResponse createDeleteUserResponse() {
        return new DeleteUserResponse();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

}
